### PR TITLE
switch to a stable embedded-hal release

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d913716 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d9137161cedd82e245ffd772d5d8f9e8ae6d56e6 with merge 86d491d3cec2485d61071b73c72e2be94b48f8ae...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/332483981?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 369046d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 369046d10413860b95a3642ba9de6de4554b76e7 with merge 46854bcef0ffe1af9386aba02ca9957cf3b99dbb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/332487483?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9a56fae has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9a56fae754fd1e532eb6c8fc86458ae866508efe with merge 789d12d9d98d6036eea92801abd5dcf1b396c963...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3f405fc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3f405fc736f7bd948fa7e9a4e142635ea6aeaaf1 with merge 68c4f12fff5a570c9e72f28e246e121cca3f876a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/332495884?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 73b545c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 73b545c5511b60e6393d86ea8f6cd04cf2ffc0d3 with merge e6b8886db8f466876afc83e12f8ec99bdb166c55...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/332523157?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e6b8886db8f466876afc83e12f8ec99bdb166c55 to master...

**Pull request merged**
