### PR TITLE
tweak the Pi example

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5334651 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5334651a6a592391b7aeb681689c0c97d79612be with merge 2e1b5ec52360369884fc1750b1d1120129c6be6b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309790141?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2e1b5ec52360369884fc1750b1d1120129c6be6b to master...

**Pull request merged**
