### PR TITLE
IMU / MARG split, filters, more selective measurements

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4a21fba has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4a21fba2be7a527f6465acfbeea43b79f693d537 with merge 539b48334e78a038bbf722c29b05fbd2d9be0758...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/335683568?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 38d50f9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 38d50f9701118b2d659feb8ad60b730e5e126772 with merge 4cd19cc74d71de6f3edf532d53537ab67c70d514...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/335703508?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/335703508?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 4cd19cc74d71de6f3edf532d53537ab67c70d514 to master...

**Pull request merged**
