### PR TITLE
ci

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6ab606d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6ab606d04ca75630e38477a58cc7f77bba66b92d with merge 7c1b7f9e332bede9484c4fc7d4b5ec7a0dd50b3b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309448699?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 7c1b7f9e332bede9484c4fc7d4b5ec7a0dd50b3b to master...

**Pull request merged**
