### PR TITLE
magnetometer support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0b0386a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0b0386aeb7036739ea9a84134ec926ed60af00a4 with merge 9b677876905c8640c1cba9b345b1b29166d56fb2...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309885635?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2538a6c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2538a6cdb8a78052692cea1116c5e6cc78cdfa69 with merge b5b6d82f64996e57ef7a88699bf2733afd7c5d35...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309909450?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b5b6d82f64996e57ef7a88699bf2733afd7c5d35 to master...

**Pull request merged**
