### PR TITLE
add RPi example

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d308ceb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d308ceb848d2aa8aa8194d74bb301e953011a6a2 with merge 14043df253feaadabe665efb067fc185d13e509e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309573144?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 889a066 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 889a06614ac9754b449a5f4ccebe5b1704c5119e with merge 006819a1c38b020bfdce8dcfec6952243180ad98...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309575504?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4bdaaac has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4bdaaac89c474fb421525ee17093517f0557eb05 with merge dcd1389fdff685fb4b016f350e575cdfb51b7e9c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309577631?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 97bd3fc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 97bd3fcc18f200020181fc6d92bce9930e1e56af with merge 3b58b637043e1a61e8a720c5ec30a0b583fa8787...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mpu9250/builds/309579775?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3b58b637043e1a61e8a720c5ec30a0b583fa8787 to master...

**Pull request merged**
